swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger log extractor
  description: API description for log extractor project
tags:
  - name: persons
    description: Operations about a person
  - name: logs
    description: Operations about logs
basePath: "/logextractor/v1"
schemes:
  - https
  - http
paths:
  '/persons/person-id':
    post:
      tags:
        - persons
      operationId: getPersonUniqueIdentifier
      summary: Get the person's unique identifier
      description: Return the person's unique identifier
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "PersonPersonId"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/PersonPersonIdRequest"
      responses:
        '200':
          description: The operation has been successfully completed
          schema:
            $ref: '#/definitions/PersonData'
        '400':
          description: In case of errors during the request validation, an error message is returned
          schema:
            $ref: '#/definitions/ApiError400'
        '500':
          description: In case of errors during the request elaboration, an error message is returned
          schema:
            $ref: '#/definitions/ApiError500'
  '/persons/tax-id':
    post:
      tags:
        - persons
      operationId: getPersonTaxId
      summary: Get the person's unique identifier
      description: Return the person's tax id
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "PersonTaxId"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/PersonTaxIdRequest"
      responses:
        '200':
          description: The operation has been successfully completed
          schema:
            $ref: '#/definitions/PersonData'
        '400':
          description: In case of errors during the request validation, an error message is returned
          schema:
            $ref: '#/definitions/ApiError400'
        '500':
          description: In case of errors during the request elaboration, an error message is returned
          schema:
            $ref: '#/definitions/ApiError500'
  '/logs/notifications/info':
    post:
      tags:
      - "logs"
      summary: "Download the logs' archive containing the full info of a notification"
      description: ""
      operationId: "getNotificationsInfoLogs"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "NotificationInfo"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/NotificationInfo"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DownloadArchive'
        '400':
          description: In case of errors during the request validation, an error message is returned
          schema:
            $ref: '#/definitions/ApiError400'
        '500':
          description: In case of errors during the request elaboration, an error message is returned
          schema:
            $ref: '#/definitions/ApiError500'
  '/logs/operators':
    post:
      tags:
      - "logs"
      summary: "Download the logs' archive related to a person activities and its operators' ones"
      description: "Download the zip file and return the password to be shown to the user"
      operationId: "getOperatorsLogs"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "NotificationInfo"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/OperatorsInfo"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DownloadArchive'
        '400':
          description: In case of errors during the request validation, an error message is returned
          schema:
            $ref: '#/definitions/ApiError400'
        '500':
          description: In case of errors during the request elaboration, an error message is returned
          schema:
            $ref: '#/definitions/ApiError500'
  '/logs/notifications/monthly':
    post:
      tags:
      - "logs"
      summary: "Download the logs' archive containing the notifications sent in a specific month"
      description: "Download the zip file and return the password to be shown to the user"
      operationId: "getNotificationsMonthlyStatsLogs"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "MonthlyNotificationsInfo"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/MonthlyNotifications"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DownloadArchive'
        '400':
          description: In case of errors during the request validation, an error message is returned
          schema:
            $ref: '#/definitions/ApiError400'
        '500':
          description: In case of errors during the request elaboration, an error message is returned
          schema:
            $ref: '#/definitions/ApiError500'
  '/logs/persons':
    post:
      tags:
      - "logs"
      summary: "Download the logs' archive related to a person's own activities or on a notification"
      description: "Download the zip file and return the password to be shown to the user"
      operationId: "getPersonsLogs"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "PersonsLogInfo"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/PersonsData"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DownloadArchive'
        '400':
          description: In case of errors during the request validation, an error message is returned
          schema:
            $ref: '#/definitions/ApiError400'
        '500':
          description: In case of errors during the request elaboration, an error message is returned
          schema:
            $ref: '#/definitions/ApiError500'
  '/logs/processes':
    post:
      tags:
      - "logs"
      summary: "Download the logs' archive related to a process"
      description: "Download the zip file and return the password to be shown to the user"
      operationId: "getProcessesLogs"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "ProcessesLogInfo"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/PersonsData"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DownloadArchive'
        '400':
          description: In case of errors during the request validation, an error message is returned
          schema:
            $ref: '#/definitions/ApiError400'
        '500':
          description: In case of errors during the request elaboration, an error message is returned
          schema:
            $ref: '#/definitions/ApiError500'
definitions:
  PersonTaxIdRequest:
    type: object
    required:
      - personId
    properties:
      personId:
        type: string
  PersonPersonIdRequest:
    type: object
    required:
      - ticketNumber
      - taxId
      - recipientType
    properties:
      ticketNumber:
        type: string
      taxId:
        type: string
      recipientType:
        type: string
        enum: [ "PF", "PG"]
  DownloadArchive:
    type: object
    required:
      - password
      - zip
    properties:
      password:
        type: string
      zip:
        type: string
        format: byte
  PersonsData:
    type: object
    required:
      - ticketNumber
      - deanonimization
    properties:
      ticketNumber:
        type: string
      deanonimization:
        type: boolean
      taxId:
        type: string
      personId:
        type: string
      iun:
        type: string
      dateFrom:
        type: string
      dateTo:
        type: string
  MonthlyNotifications:
    type: object
    required:
      - ticketNumber
      - ipaCode
      - referenceMonth
    properties:
      ticketNumber:
        type: string
      ipaCode:
        type: integer
      referenceMonth:
        type: string
  OperatorsInfo:
    type: object
    required:
      - ticketNumber
      - taxId
      - dateFrom
      - dateTo
    properties:
      ticketNumber:
        type: string
      taxId:
        type: string
      dateFrom:
        type: string
      dateTo:
        type: string
  NotificationInfo:
    type: object
    required:
      - ticketNumber
      - iun
    properties:
      ticketNumber:
        type: string
      iun:
        type: string
  PersonData:
    type: object
    required:
      - data
    properties:
      data:
        type: string
        example: qwerty
  ApiError400:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        example: Informazioni non valide
  ApiError500:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        example: Errore nell'elaborazione della richiesta