AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of Log Extractor alarms subsystem


Parameters:
  OpenSearchClusterName:
    Type: String
    Description: Name of the OpenSearch cluster

  ProjectName:
    Type: String
    Description: Name of the project

  AlarmSNSTopicArn:
    Type: String
    Description: Alarm SNS Topic ARN

Resources:
  ClusterStatusRed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-cluster-red"
      AlarmDescription: "Email when ClusterStatus.red >=1, 1 time within 1 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "ClusterStatus.red"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      EvaluationPeriods: 1
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  ClusterStatusYellow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-cluster-yellow"
      AlarmDescription: "Email when ClusterStatus.yellow >=1, 1 time within 1 minute"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "ClusterStatus.yellow"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      EvaluationPeriods: 1
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  FreeStorageSpace:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-low-storage"
      AlarmDescription: "Email when FreeStorageSpace <= 20%, 1 time within 1 minute"
      Metrics:
        - Id: m1
          MetricStat:
            Metric:
              Dimensions:
                - Name: ClientId
                  Value: !Ref AWS::AccountId
                - Name: DomainName
                  Value: 
                    Ref: OpenSearchClusterName
              MetricName: FreeStorageSpace
              Namespace: AWS/ES
            Period: 60
            Stat: Maximum
          ReturnData: False
        - Id: m2
          MetricStat:
            Metric:
              Dimensions:
                - Name: ClientId
                  Value: !Ref AWS::AccountId
                - Name: DomainName
                  Value: 
                    Ref: OpenSearchClusterName
              MetricName: ClusterUsedSpace
              Namespace: AWS/ES
            Period: 60
            Stat: Maximum
          ReturnData: False
        - Id: e1
          Expression: (m1*100)/(m1+m2)
          Label: !Sub "${ProjectName}-avg free space"
      ComparisonOperator: LessThanOrEqualToThreshold
      Threshold: 20
      EvaluationPeriods: 1
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  ClusterIndexWritesBlocked:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-writes-blocked"
      AlarmDescription: "Email when ClusterIndexWritesBlocked >=1, 1 time within 5 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "ClusterIndexWritesBlocked"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 300
      EvaluationPeriods: 1
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  CPUUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-cpu-usage"
      AlarmDescription: "Email when CPUUtilization >=80, 3 time within 15 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "CPUUtilization"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 80
      Period: 900
      EvaluationPeriods: 3
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  JVMMemoryPressure:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-jvm-pressure"
      AlarmDescription: "Email when JVMMemoryPressure >= 95, 3 time within 5 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "JVMMemoryPressure"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 95
      Period: 300
      EvaluationPeriods: 3
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  MasterCPUUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-master-cpu"
      AlarmDescription: "Email when MasterCPUUtilization >= 50, 3 time within 15 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "MasterCPUUtilization"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 50
      Period: 900
      EvaluationPeriods: 3
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  MasterJVMMemoryPressure:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-master-jvm-pressure"
      AlarmDescription: "Email when MasterJVMMemoryPressure >= 95, 1 time within 15 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "MasterJVMMemoryPressure"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 95
      Period: 900
      EvaluationPeriods: 1
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn
