AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of Log Extractor alarms subsystem


Parameters:
  OpenSearchClusterName:
    Type: String
    Description: Name of the OpenSearch cluster

  ProjectName:
    Type: String
    Description: Name of the project

  AlarmSNSTopicArn:
    Type: String
    Description: Alarm SNS Topic ARN

  ApiGwLatencyLimit:
    Default: 1000
    Type: Number
    Description: Latency limit before raising alarm (milliseconds)

  EnvType:
    Type: String
    Description: Environment Type

  OpenSearchMasterNodeType:
    Default: ""
    Type: String
    Description: Environment Type

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

Conditions:
  HasMasterNode: !Not [ !Equals [ !Ref OpenSearchMasterNodeType, "" ] ]

Resources:
  ClusterStatusRed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-cluster-red"
      AlarmDescription: "Email when ClusterStatus.red >=1, 1 time within 1 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "ClusterStatus.red"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      EvaluationPeriods: 1
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  ClusterStatusYellow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-cluster-yellow"
      AlarmDescription: "Email when ClusterStatus.yellow >=1, 1 time within 1 minute"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "ClusterStatus.yellow"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      EvaluationPeriods: 1
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  FreeStorageSpace:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-low-storage"
      AlarmDescription: "Email when FreeStorageSpace <= 20%, 1 time within 1 minute"
      Metrics:
        - Id: m1
          MetricStat:
            Metric:
              Dimensions:
                - Name: ClientId
                  Value: !Ref AWS::AccountId
                - Name: DomainName
                  Value: 
                    Ref: OpenSearchClusterName
              MetricName: FreeStorageSpace
              Namespace: AWS/ES
            Period: 60
            Stat: Maximum
          ReturnData: False
        - Id: m2
          MetricStat:
            Metric:
              Dimensions:
                - Name: ClientId
                  Value: !Ref AWS::AccountId
                - Name: DomainName
                  Value: 
                    Ref: OpenSearchClusterName
              MetricName: ClusterUsedSpace
              Namespace: AWS/ES
            Period: 60
            Stat: Maximum
          ReturnData: False
        - Id: e1
          Expression: (m1*100)/(m1+m2)
          Label: !Sub "${ProjectName}-avg free space"
      ComparisonOperator: LessThanOrEqualToThreshold
      Threshold: 20
      EvaluationPeriods: 1
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  ClusterIndexWritesBlocked:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-writes-blocked"
      AlarmDescription: "Email when ClusterIndexWritesBlocked >=1, 1 time within 5 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "ClusterIndexWritesBlocked"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 300
      EvaluationPeriods: 1
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  CPUUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-cpu-usage"
      AlarmDescription: "Email when CPUUtilization >=80, 3 time within 15 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "CPUUtilization"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 80
      Period: 900
      EvaluationPeriods: 3
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  JVMMemoryPressure:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-jvm-pressure"
      AlarmDescription: "Email when JVMMemoryPressure >= 95, 3 time within 5 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "JVMMemoryPressure"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 95
      Period: 300
      EvaluationPeriods: 3
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  MasterCPUUtilization:
    Type: AWS::CloudWatch::Alarm
    Condition: HasMasterNode
    Properties:
      AlarmName: !Sub "${ProjectName}-master-cpu"
      AlarmDescription: "Email when MasterCPUUtilization >= 50, 3 time within 15 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "MasterCPUUtilization"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 50
      Period: 900
      EvaluationPeriods: 3
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  MasterJVMMemoryPressure:
    Type: AWS::CloudWatch::Alarm
    Condition: HasMasterNode
    Properties:
      AlarmName: !Sub "${ProjectName}-master-jvm-pressure"
      AlarmDescription: "Email when MasterJVMMemoryPressure >= 95, 1 time within 15 minutes"
      Namespace: "AWS/ES"
      Dimensions:
        - Name: ClientId
          Value: !Ref AWS::AccountId
        - Name: DomainName
          Value:
            Ref: OpenSearchClusterName
      Statistic: Maximum
      MetricName: "MasterJVMMemoryPressure"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 95
      Period: 900
      EvaluationPeriods: 1
      OKActions:
        - !Ref AlarmSNSTopicArn
      AlarmActions:
        - !Ref AlarmSNSTopicArn

  LogextractorFatalLogsMetricAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-Logextractor-ErrorFatalLogs-Alarm"
      AlarmDescription: "CloudWatch alarm for when ECS LogGroup has ERROR or FATAL line."
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      OKActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: 1
      MetricName: !Sub "pn-logextractor-be-${EnvType}-ErrorFatalMetric"
      Namespace: "ErrorFatalLogs"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  # Rest API CloudWatch alarm 
  APIGatewayApiLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-ApiGwLatencyAlarm"
      AlarmDescription: "CloudWatch alarm for when API Gateway latency exceeds the limit."
      AlarmActions: 
        - !Ref AlarmSNSTopicArn
      InsufficientDataActions:
        - !Ref AlarmSNSTopicArn
      OKActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: 3
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      Threshold: !Ref ApiGwLatencyLimit
      TreatMissingData: notBreaching
      Namespace: "AWS/ApiGateway"
      MetricName: "Latency"
      Period: 60
      Dimensions:
        - Name: ApiName
          Value: !Sub 'pn-logextractor-${EnvType}-public-api'
      ExtendedStatistic: "p95"

  APIGatewayApiErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-ApiGwAlarm"
      AlarmDescription: "CloudWatch alarm for when API Gateway has 4xx or 5xx error."
      AlarmActions: 
        - !Ref AlarmSNSTopicArn
      InsufficientDataActions:
        - !Ref AlarmSNSTopicArn
      OKActions:
        - !Ref AlarmSNSTopicArn
      DatapointsToAlarm: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      Threshold: 1
      TreatMissingData: notBreaching
      Metrics:
        - Id: m1
          MetricStat:
            Metric:
              Dimensions:
                - Name: ApiName
                  Value: !Sub 'pn-logextractor-${EnvType}-public-api'
              MetricName: 4XXError
              Namespace: AWS/ApiGateway
            Period: 60
            Stat: Sum
          ReturnData: False
        - Id: m2
          MetricStat:
            Metric:
              Dimensions:
                - Name: ApiName
                  Value: !Sub 'pn-logextractor-${EnvType}-public-api'
              MetricName: 5XXError
              Namespace: AWS/ApiGateway
            Period: 60
            Stat: Sum
          ReturnData: False
        - Id: e1
          Expression: SUM([m1,m2])
          Label: !Sub "${ProjectName}-APIGatewayErrorMetric"

  CloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-dashboard"
        AlarmArns: !Join
          - ','
          - - !GetAtt APIGatewayApiErrorAlarm.Arn
            - !GetAtt APIGatewayApiLatencyAlarm.Arn
            - !GetAtt LogextractorFatalLogsMetricAlarm.Arn
            - !GetAtt ClusterIndexWritesBlocked.Arn
            - !GetAtt ClusterStatusRed.Arn
            - !GetAtt ClusterStatusYellow.Arn
            - !GetAtt FreeStorageSpace.Arn