AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of cognito

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project

Resources:
  CognitoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-cognito