AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of Log Extractor system


Parameters:
  CloudFrontLogBucketDomainName:
    Type: String
    Description: Bucket to store CloudFront logs

  ProjectName:
    Type: String
    Description: Name of the project

  TemplateBucketBaseUrl:
    Type: String
    Description: The S3 bucket from which to fetch the templates used by this stack

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: Id of the VPC to deploy resources into

  PrivateSubnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: Private subnets of the given VPC

  HostedZoneId:
    Type: String
    Description: Hosted Zone ID

  WebDomain:
    Type: String
    Description: Web domain name

  WebDomainReferenceToSite:
    Description: true if the website must be reachable using the WebDomain
    Type: String
    Default: 'true'

  AlternateWebDomain:
    Description: "Alternate Domain name for the webapp"
    Type: String
    Default: ''

  AlternateWebDomainReferenceToSite:
    Description: true if the website must be reachable using the AlternateWebDomain
    Type: String
    Default: 'true' 

  AlternateHostedZoneId:
    Description: Hosted Zone Id in which you want to add alternate DNS
    Type: String
    Default: ''

  WebCertificateArn:
    Description: "ACM Web Certificate ARN"
    Type: String
    
  ApiUrl:
    Description: "Helpdesk API Base URL"
    Type: String
  
  CoreApiUrl:
    Description: "Core API Url"
    Type: String

Resources:
  Frontend:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        HostedZoneId: !Ref HostedZoneId
        WebDomain: !Ref WebDomain
        WebDomainReferenceToSite: !Ref WebDomainReferenceToSite
        AlternateWebDomain: !Ref AlternateWebDomain
        AlternateWebDomainReferenceToSite: !Ref AlternateWebDomainReferenceToSite
        AlternateHostedZoneId: !Ref AlternateHostedZoneId
        WebCertificateArn: !Ref WebCertificateArn
        ApiUrl: !Ref ApiUrl
        CoreApiUrl: !Ref CoreApiUrl
        LogBucketDomainName: !Ref CloudFrontLogBucketDomainName
        ProjectName: !Ref ProjectName
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/frontend.yaml

Outputs:
  DistributionId:
    Value: !GetAtt Frontend.Outputs.DistributionId

  DistributionDomainName:
    Value: !GetAtt Frontend.Outputs.DomainName
  