AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of Log Extractor system (global)


Parameters:
  ProjectName:
    Type: String
    Description: Name of the project

Resources:
  LogsStorage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-infra