AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of Log Extractor system


Parameters:
  ApiCognitoUserPoolArn:
    Type: String
    Description: User Pool ARN to authenticate API requests

  ApiLogRetentionInDays:
    Type: Number
    Default: 14
    Description: Number of days to preserve the API logs

  ProjectName:
    Type: String
    Description: Name of the project

  TemplateBucketBaseUrl:
    Type: String
    Description: The S3 bucket from which to fetch the templates used by this stack

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: Id of the VPC to deploy resources into

  PrivateSubnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: Private subnets of the given VPC

Resources:
  Backend:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        SubnetIds: !Join [',', !Ref PrivateSubnetIds]
        VpcId: !Ref VpcId
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/backend.yaml

  Api:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        NetworkLoadBalancerDomain: !GetAtt Backend.Outputs.NlbDomain
        CognitoUserPoolArn: !Ref ApiCognitoUserPoolArn
        LogRetentionInDays: !Ref ApiLogRetentionInDays
        NetworkLoadBalancerLink: !GetAtt Backend.Outputs.NlbLink
        ProjectName: !Ref ProjectName
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/api.yaml

Outputs:
  AlbListenerArn:
    Value: !GetAtt Backend.Outputs.AlbListenerArn
  
  ApiDomain:
    Value: !Sub ${Api.Outputs.RestApiId}.execute-api.${AWS::Region}.amazonaws.com

  ApiId:
    Value: !GetAtt Api.Outputs.RestApiId

  ApiStageName:
    Value: !GetAtt Api.Outputs.RestApiStageName