AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of Log Extractor system


Parameters:
  ApiCognitoUserPoolArn:
    Type: String
    Description: User Pool ARN to authenticate API requests

  ApiLogRetentionInDays:
    Type: Number
    Default: 14
    Description: Number of days to preserve the API logs

  ProjectName:
    Type: String
    Description: Name of the project

  TemplateBucketBaseUrl:
    Type: String
    Description: The S3 bucket from which to fetch the templates used by this stack

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: Id of the VPC to deploy resources into

  PrivateSubnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: Private subnets of the given VPC

  HostedZoneId:
    Type: String
    Description: Hosted Zone ID

  ApiDomain:
    Type: String
    Description: Api domain name

  AlternateApiDomain:
    Description: "Alternate Domain name for the API"
    Type: String
    Default: ''

  ApiCertificateArn:
    Description: "ACM Api Certificate ARN"
    Type: String

Conditions:
  HasAlternateApiDomain: !Not 
    - !Equals
      - !Ref AlternateApiDomain
      - ""

Resources:
  
  ###                       CLOUDFORMATION TRANSFORM LAMBDAS              ###
  ###########################################################################

  UpdateDeploymentTransform:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/lambda-update-deployment-transform.yaml"

  Backend:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        SubnetIds: !Join [',', !Ref PrivateSubnetIds]
        VpcId: !Ref VpcId
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/backend.yaml

  ###            COMMON RESOURCES FOR WEB API AND DISTRIBUTIONS            ###
  ############################################################################
  RestApiCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: 
        Fn::If:
          - HasAlternateApiDomain
          - !Ref AlternateApiDomain
          - !Ref ApiDomain 
      RegionalCertificateArn: !Ref ApiCertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL
      SecurityPolicy: TLS_1_2

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref ApiDomain
      Type: A
      HostedZoneId: !Ref HostedZoneId
      AliasTarget:
        DNSName: !GetAtt RestApiCustomDomain.RegionalDomainName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt RestApiCustomDomain.RegionalHostedZoneId

  Api:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - UpdateDeploymentTransform
    Properties:
      Parameters:
        NetworkLoadBalancerDomain: !GetAtt Backend.Outputs.NlbDomain
        CognitoUserPoolArn: !Ref ApiCognitoUserPoolArn
        LogRetentionInDays: !Ref ApiLogRetentionInDays
        NetworkLoadBalancerLink: !GetAtt Backend.Outputs.NlbLink
        ProjectName: !Ref ProjectName
        ServiceApiPath: logextractor
        ApiDomain: 
          Fn::If:
            - HasAlternateApiDomain
            - !Ref AlternateApiDomain
            - !Ref ApiDomain
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/api.yaml

Outputs:
  AlbListenerArn:
    Value: !GetAtt Backend.Outputs.AlbListenerArn
  
  ApiDomain:
    Value: 
      Fn::If:
        - HasAlternateApiDomain
        - !Ref AlternateApiDomain
        - !Ref ApiDomain

  AlbSecurityGroup:
    Value: !GetAtt Backend.Outputs.AlbSecurityGroup

  ApiId:
    Value: !GetAtt Api.Outputs.RestApiId

  ApiStageName:
    Value: !GetAtt Api.Outputs.RestApiStageName