AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of Log Extractor system


Parameters:
  CacheNodeType:
    Type: String
    Default: cache.t3.micro
    Description: Type of the nodes in the cache cluster

  CacheReplicas:
    Type: Number
    Default: 1
    Description: Number of nodes in the cache cluster

  OpenSearchEbsIops:
    Type: Number
    Description: OpenSearch node volume iops

  OpenSearchEbsSize:
    Type: Number
    Description: OpenSearch node volume size (in GiB)

  OpenSearchEbsType:
    Type: String
    Description: OpenSearch node volume type such as standard, gp2, or io1

  OpenSearchEngineVersion:
    Type: String
    Default: OpenSearch_1.2
    Description: OpenSearch engine version

  OpenSearchNodeReplicas:
    Type: Number
    Description: OpenSearch node replicas

  OpenSearchNodeType:
    Type: String
    Description: OpenSearch nodes type

  OpenSearchMasterCredentialSecret:
    Type: String
    Description: OpenSearch master credential secret

  OpenSearchMasterNodeType:
    Type: String
    Default: ""
    Description: OpenSearch Master nodes type
  
  OpenSearchMasterNodeInstanceNumber:
    Type: Number
    Description: Dedicated master nodes number for OpenSearch cluster

  ProjectName:
    Type: String
    Description: Name of the project

  TemplateBucketBaseUrl:
    Type: String
    Description: The S3 bucket from which to fetch the templates used by this stack

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: Id of the VPC to deploy resources into

  PrivateSubnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: Private subnets of the given VPC

Resources:
  Cache:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        NodeType: !Ref CacheNodeType
        ProjectName: !Ref ProjectName
        Replicas: !Ref CacheReplicas
        SubnetIds: !Join [',', !Ref PrivateSubnetIds]
        VpcId: !Ref VpcId
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/cache.yaml

  OpenSearch:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        EbsIops: !Ref OpenSearchEbsIops
        EbsVolumeSize: !Ref OpenSearchEbsSize
        EbsVolumeType: !Ref OpenSearchEbsType
        EngineVersion: !Ref OpenSearchEngineVersion
        InstanceReplicas: !Ref OpenSearchNodeReplicas
        InstanceType: !Ref OpenSearchNodeType
        MasterNodeType: !Ref OpenSearchMasterNodeType
        MasterNodeInstancesNumber: !Ref OpenSearchMasterNodeInstanceNumber
        ProjectName: !Ref ProjectName
        SubnetIds: !Join [',', !Ref PrivateSubnetIds]
        VpcId: !Ref VpcId
        MasterCredentialSecret: !Ref OpenSearchMasterCredentialSecret
      TemplateURL: !Sub ${TemplateBucketBaseUrl}/fragments/opensearch.yaml

  AlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: 'helpdesk account alarms topic'

Outputs:
  ElasticacheEndpoint:
    Description: Elasticache endpoint
    Value: !GetAtt Cache.Outputs.RedisEndpoint
  
  ElasticacheSecurityGroup:
    Value: !GetAtt Cache.Outputs.AllowedSecurityGroupId

  OpenSearchEndpoint:
    Description: OpenSearch endpoint
    Value: !GetAtt OpenSearch.Outputs.DomainEndpoint
  
  OpenSearchClusterName:
    Description: OpenSearch cluster name
    Value: !GetAtt OpenSearch.Outputs.ClusterName

  AlarmSNSTopicArn:
    Value: !Ref AlarmSNSTopic
    Description: ARN of the Alarm SNS Topic

  AlarmSNSTopicName:
    Value: !GetAtt  AlarmSNSTopic.TopicName
    Description: Name of the Alarm SNS Topic