AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione
  
  EnvironmentType:
    Type: String
    Description: 'Environment type dev,test,...'

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  LogRetention:
    Type: Number
    Default: 14

Resources:

  PnLogextractorBeLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-logextractor-be'
        LogGroupRetention: !Ref LogRetention

  TemporaryLogExtractionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pn-logextractor-temporary-${EnvironmentType}'
      AccessControl: 'Private'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              #  KMSMasterKeyID: KMS-KEY-AR
      CorsConfiguration:  
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - 'GET'
              - 'PUT'
              - 'HEAD'
              - 'POST'
              - 'DELETE'
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - 'x-amz-version-id'
            MaxAge: 3600
            Id: 'CORSRuleSafeStorage'
      LifecycleConfiguration:
        Rules:
          - Id: 'AbortIncompleteMultipartUpload'
            AbortIncompleteMultipartUpload: 
                DaysAfterInitiation: 1
            Status: 'Enabled'
          - Id: 'RemoveFilesAfterOneDay'
            ExpirationInDays: 1
            Status: 'Enabled'
            Prefix: '' 
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
          
Outputs:
  
  # Log group exports
  EcsLogGroup:
    Value: !GetAtt PnLogextractorBeLogGroup.Outputs.LogGroupName
  
  TmpBucketName:
    Value: !Sub 'pn-logextractor-temporary-${EnvironmentType}'

