AWSTemplateFormatVersion: "2010-09-09"

Description: |
  CloudFormation definition of Log Extractor additional services


Parameters:
  EbsIops:
    Type: Number
    Description: The number of I/O operations per second (IOPS) that the volume supports

  EbsVolumeSize:
    Type: Number
    Description: The size (in GiB) of the EBS volume for each data node

  EbsVolumeType:
    Type: String
    Description: The EBS volume type to use with the OpenSearch Service domain, such as standard, gp2, or io1

  EngineVersion:
    Type: String
    Description: User-defined OpenSearch version

  InstanceReplicas:
    Type: Number
    Default: 3
    Description: Number of instances

  InstanceType:
    Type: String
    Description: "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html"

  MasterNodeType:
    Type: String
    Description: "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html Master Node Instance Type"
    Default: ""
    
  MasterNodeInstancesNumber:
    Type: Number
    Description: "Master Node Instance number"

  ProjectName:
    Type: String
    Description: Name of the project

  SubnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: Private subnets to deploy resources into

  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: VPC id of the subnets

  MasterCredentialSecret:
    Type: String
    Description: Master credential secret

Conditions:
  HasDedicatedMaster: !Not [ !Equals [ !Ref MasterNodeType, "" ] ]

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Open HTTPS port
      GroupName: !Sub ${ProjectName}-opensearch
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId: !Ref VpcId

  ### AWS KMS / Server-side encryption for Kinesis Stream 
  # https://docs.aws.amazon.com/streams/latest/dev/server-side-encryption.html
  OpenSearchEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  OpenSearchServiceDomain:
    Type: "AWS::OpenSearchService::Domain"
    Properties:
      AccessPolicies:
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "es:ESHttp*"
            Resource: "*"
        Version: "2012-10-17"
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: !GetAtt OpenSearchEncryptionKey.KeyId
      NodeToNodeEncryptionOptions:
        Enabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions: 
          MasterUserName: !Sub '{{resolve:secretsmanager:${MasterCredentialSecret}:SecretString:username}}'
          MasterUserPassword: !Sub '{{resolve:secretsmanager:${MasterCredentialSecret}:SecretString:password}}'
      ClusterConfig:
        !If 
          - HasDedicatedMaster
          - InstanceCount: !Ref InstanceReplicas
            InstanceType: !Ref InstanceType
            DedicatedMasterCount: !Ref MasterNodeInstancesNumber
            DedicatedMasterEnabled: true
            DedicatedMasterType: !Ref MasterNodeType
            ZoneAwarenessConfig:
              AvailabilityZoneCount: 3
            ZoneAwarenessEnabled: true
          - InstanceCount: !Ref InstanceReplicas
            InstanceType: !Ref InstanceType
            DedicatedMasterEnabled: false
            ZoneAwarenessConfig:
              AvailabilityZoneCount: 3
            ZoneAwarenessEnabled: true
      EBSOptions:
        EBSEnabled: true
        Iops: !Ref EbsIops
        VolumeSize: !Ref EbsVolumeSize
        VolumeType: !Ref EbsVolumeType
      EngineVersion: !Ref EngineVersion
      VPCOptions:
        SecurityGroupIds:
          - Ref: SecurityGroup
        SubnetIds: !Ref SubnetIds
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
Outputs:
  ClusterName:
    Description: The name of the OpenSearch Service domain
    Value: !Ref OpenSearchServiceDomain

  DomainEndpoint:
    Value: !GetAtt OpenSearchServiceDomain.DomainEndpoint